server:
  port: 6063
---
application:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: 'jdbc:postgresql://localhost:6301/url_shortener'
    username: root
    password: '12345678'
---
url-shortener:
  base-url: http://localhost:6063
